name: My Workflow

on:
  push:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 2"

  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 3"

  job4:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 4"

  job5:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 5"

  job6:
    needs:
      - job4
      - job5
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Job 6"